name: 'Deploy Only Changed'
description: 'Greet someone and record the time'
inputs:
  project-id:
    description: 'ID of Google Cloud Project'
    required: true
  token:
    description: 'Firebase CI token (used for deploy call).'
  functions-folder:
    description: 'Folder where functions live'
    default: 'functions'
  ignore:
    description: 'Globs to ignore in diffing (i.e *.test.js)'
  skip-deploy:
    description: 'Whether or not to skip deploy'
  cache-folder:
    description: 'Folder to use for cache'
  local-folder:
    description: 'Local folder to use for cache'
  storage-bucket:
    description: 'Cloud Storage Bucket'
runs:
  using: 'node12'
  main: 'dist/index.js'