name: NPM Package Publish

on:
  push:
    branches:
      - master
      - next
      - alpha

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1

      - name: Use Node 12
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          
      - name: Cache npm run Dependencies
        if: steps.check.outputs.changed == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Check For Lint
        if: steps.check.outputs.changed == 'true'
        run: npm run lint

      - name: Run Unit Tests + Coverage
        if: steps.check.outputs.changed == 'true'
        env:
          CODE_CLIMATE: ${{ secrets.CODE_CLIMATE }}
        run: npm run test:cov

      - name: Run Build
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          gitBranch=${GITHUB_REF##*/}
          packageVersion=$(cat package.json | jq -r '.version')
          publishFlag=$(if [ "$GITHUB_REF" != 'refs/heads/master' ]; then eval echo '--tag $gitBranch'; else echo ''; fi;)
          echo "::set-env name=PACKAGE_VERSION::$packageVersion"
          npm publish $publishFlag

      - name: Archive Build Artifact
        if: steps.check.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: lib

      # Upload to codecov.io. Curl used in place of codecov/codecov-action
      # due to long build time. See https://github.com/codecov/codecov-action/issues/21
      - name: Upload Coverage
        if: steps.check.outputs.changed == 'true'
        run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: github.ref != 'refs/heads/master'