name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Cache npm run Dependencies
        if: steps.check.outputs.changed == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Check For Lint
        run: npm run lint

      - name: Run Unit Tests + Coverage
        run: npm run test:cov

      # Upload to codecov.io. Curl used in place of codecov/codecov-action
      # due to long build time. See https://github.com/codecov/codecov-action/issues/21
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

      - name: Run Build
        run: npm run build
